apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ingress.yaml

components:
- github.com/ZeitOnline/kustomize/components/postgrest?ref=1.11

images:
- name: postgrest
  newName: postgrest/postgrest
  newTag: v12.2.3

patches:
- path: config.yaml
- target:
    kind: Deployment
    name: postgrest
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/readinessProbe/httpGet
      value:
        path: /ready # if we add the /pgrest/ prefix, do we need to change this path?
        port: 3001
        scheme: HTTP
    - op: add
      path: /spec/template/spec/containers/-
      value:
        name: cloud-sql-proxy
        command:
        - /cloud-sql-proxy
        - $(INSTANCE_CONNECTION)
        - --auto-iam-authn
        - --address=0.0.0.0
        env:
        - name: INSTANCE_CONNECTION
          valueFrom:
            secretKeyRef:
              key: INSTANCE_CONNECTION
              name: cloudsql-proxy-iam
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.2@sha256:fd2baaf9c709598e54838a6875833759412033ab5ee578cc81f9825fa34bd296
        securityContext:
          runAsNonRoot: true