name: Build and Test
on:
  push:
    tags:
        - '*'

env:
  ENVIRONMENT: production
  PROJECT: spiele-backoffice
  IMAGE: backoffice
  REGISTRY: ${{ vars.GAR_DOCKER_REGISTRY }}

jobs:
  build:
    name: Build
    runs-on: zon-ubuntu-general-dind

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: extraxt version
        shell: bash
        run: |
          REF=${{ github.ref_name }}
          TAG=${REF#${{ inputs.context }}-}
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Baseproject
        id: baseproject
        uses: ZeitOnline/gh-action-baseproject@v0
        with:
          project_name: ${{ env.PROJECT }}
          environment: ${{ env.ENVIRONMENT }}
          gar_docker_auth: true

      - name: Build and push image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          context: .
          file: Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}
