name: Pull Request Labeler
on:
- pull_request_target
jobs:
  triage:
    name: Apply labels
    runs-on: zon-ubuntu-general-dind
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/labeler@v5
